openapi: 3.0.0
info:
  contact:
    name: gemiros
  description: SW2.5の各種データに対するバックエンドAPI
  title: SW25DB
  version: "1.0"
servers:
- url: http://localhost:3000
tags:
- name: monster
paths:
  /monsters:
    delete:
      description: モンスターデータの削除
      operationId: delete-monsters
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/delete_monsters_request'
      responses:
        "200":
          description: OK
      summary: ""
      tags:
      - monster
    get:
      description: 全てのモンスターデータを取得する
      operationId: get-monsters
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_monsters_200_response'
          description: OK
      summary: Your GET endpoint
      tags:
      - monster
    post:
      description: モンスターデータの投稿
      operationId: post-monsters
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/post_monsters_request'
      responses:
        "200":
          description: OK
      summary: ""
      tags:
      - monster
    put:
      description: モンスターデータの修正
      operationId: put-monsters
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/put_monsters_request'
      responses:
        "200":
          description: OK
      summary: ""
      tags:
      - monster
components:
  schemas:
    CommonMonster:
      example:
        Status:
          reac: reac
          mind: mind
          imp: imp
          int: int
          speed: speed
          life: life
          weak: weak
          habi:
          - habi
          - habi
          pop: pop
          perc: perc
          preem: preem
          weakValue: weakValue
          lang:
          - lang
          - lang
        Top:
          race: race
          name: name
          lv: lv
        Parts:
        - core: true
          damage: damage
          hit: hit
          mp: mp
          name: name
          hp: hp
          avoid: avoid
          protect: protect
        - core: true
          damage: damage
          hit: hit
          mp: mp
          name: name
          hp: hp
          avoid: avoid
          protect: protect
        Abilitys:
        - explain: explain
          kind:
          - kind
          - kind
          name: name
        - explain: explain
          kind:
          - kind
          - kind
          name: name
        Explanation: Explanation
        Bootys:
        - item: item
          dice: dice
        - item: item
          dice: dice
        Tags:
        - Tags
        - Tags
      properties:
        Top:
          $ref: '#/components/schemas/MonsterTop'
        Status:
          $ref: '#/components/schemas/MonsterStatus'
        Parts:
          items:
            $ref: '#/components/schemas/MonsterParts'
          type: array
          x-stoplight:
            id: t9fgs72kz93ok
        Abilitys:
          items:
            $ref: '#/components/schemas/MonsterAbility'
          type: array
          x-stoplight:
            id: syx7z26v9ey8o
        Bootys:
          items:
            $ref: '#/components/schemas/MonsterBooty'
          type: array
          x-stoplight:
            id: xn3b252wtnugv
        Explanation:
          type: string
          x-stoplight:
            id: 6wf10yaj6od4n
        Tags:
          items:
            type: string
            x-stoplight:
              id: a0goq24seymiw
          type: array
          x-stoplight:
            id: 3es1gupndjywi
      title: CommonMonster
      type: object
      x-stoplight:
        id: 5rykczom1ayrh
    RideMonster:
      properties:
        Top:
          $ref: '#/components/schemas/MonsterTop'
        Status:
          $ref: '#/components/schemas/RideStatus'
        Parts:
          items:
            $ref: '#/components/schemas/RideParts'
          type: array
          x-stoplight:
            id: ueiehc5sleb5p
        Abilitys:
          items:
            $ref: '#/components/schemas/MonsterAbility'
          type: array
          x-stoplight:
            id: 3h4416p31sym5
        Explanation:
          type: string
          x-stoplight:
            id: o9d20dryz2b60
        Tags:
          items:
            type: string
            x-stoplight:
              id: 1nykz5xlmd225
          type: array
          x-stoplight:
            id: 183vlwpspnfvc
      title: CommonMonster
      type: object
      x-stoplight:
        id: 6w41ozxr6oozf
    GolemMonster:
      properties:
        Top:
          $ref: '#/components/schemas/MonsterTop'
        Status:
          $ref: '#/components/schemas/MonsterStatus'
        Parts:
          items:
            $ref: '#/components/schemas/MonsterParts'
          type: array
          x-stoplight:
            id: 2cyizv1ux5c60
        Abilitys:
          $ref: '#/components/schemas/GolemAbilitys'
        Bootys:
          items:
            $ref: '#/components/schemas/MonsterBooty'
          type: array
          x-stoplight:
            id: jb8yc1dek7ul1
        Explanation:
          type: string
          x-stoplight:
            id: 2jh7q2vio0s81
        Tags:
          items:
            type: string
            x-stoplight:
              id: k3u9mfked4yxv
          type: array
          x-stoplight:
            id: 0czv7wuq5zu7e
      title: CommonMonster
      type: object
      x-stoplight:
        id: 8likahyzyzymj
    FamiliaMonster:
      properties:
        Top:
          $ref: '#/components/schemas/MonsterTop'
        Status:
          $ref: '#/components/schemas/FamiliaStatus'
        Parts:
          items:
            $ref: '#/components/schemas/MonsterParts'
          type: array
          x-stoplight:
            id: 4idhf1jmme65x
        Abilitys:
          $ref: '#/components/schemas/GolemAbilitys'
        Explanation:
          type: string
          x-stoplight:
            id: cbxijntfy1sco
        Tags:
          items:
            type: string
            x-stoplight:
              id: jowdkifmimthe
          type: array
          x-stoplight:
            id: dxz9uqpwpa5hg
      title: CommonMonster
      type: object
      x-stoplight:
        id: k0zn4qoq6zgnu
    MonsterTop:
      example:
        race: race
        name: name
        lv: lv
      properties:
        race:
          type: string
          x-stoplight:
            id: ui4oz4mbwmhpp
        lv:
          type: string
          x-stoplight:
            id: mtldgbk4qbywp
        name:
          type: string
          x-stoplight:
            id: 0n03a2kte141e
      title: MonsterTop
      type: object
      x-stoplight:
        id: f6u7jg1t7dwdq
    MonsterStatus:
      example:
        reac: reac
        mind: mind
        imp: imp
        int: int
        speed: speed
        life: life
        weak: weak
        habi:
        - habi
        - habi
        pop: pop
        perc: perc
        preem: preem
        weakValue: weakValue
        lang:
        - lang
        - lang
      properties:
        int:
          type: string
          x-stoplight:
            id: ulfm4pq6zmdap
        perc:
          type: string
          x-stoplight:
            id: xmv94cdoeddkv
        reac:
          type: string
          x-stoplight:
            id: 1gus1l73d8q01
        imp:
          type: string
          x-stoplight:
            id: qb36b3k2rqgfn
        lang:
          items:
            type: string
            x-stoplight:
              id: ca8ozjt461hu4
          type: array
          x-stoplight:
            id: 2tnm5xk4pnbt5
        habi:
          items:
            type: string
            x-stoplight:
              id: jgigxe87cbt5g
          type: array
          x-stoplight:
            id: bowv51yoz0z31
        pop:
          type: string
          x-stoplight:
            id: zb6zxbkakxiql
        weakValue:
          type: string
          x-stoplight:
            id: vaa0na3trlxf3
        weak:
          type: string
          x-stoplight:
            id: 4ghk3980sq7ur
        preem:
          type: string
          x-stoplight:
            id: mm4i6szp1gz7f
        speed:
          type: string
          x-stoplight:
            id: smsijjv7ql6cr
        life:
          type: string
          x-stoplight:
            id: 0ud6kffpam5en
        mind:
          type: string
          x-stoplight:
            id: bksjkbmndohuz
      title: MonsterStatus
      type: object
      x-stoplight:
        id: dd8aed72gmkqp
    MonsterParts:
      example:
        core: true
        damage: damage
        hit: hit
        mp: mp
        name: name
        hp: hp
        avoid: avoid
        protect: protect
      properties:
        core:
          type: boolean
          x-stoplight:
            id: 58xnu1tlozawg
        name:
          type: string
          x-stoplight:
            id: 8x433v48trtiu
        hit:
          type: string
          x-stoplight:
            id: 4904cuog6hz3c
        damage:
          type: string
          x-stoplight:
            id: cvkfpk7pht0pm
        avoid:
          type: string
          x-stoplight:
            id: nn70jka3axshe
        protect:
          type: string
          x-stoplight:
            id: t5g7sdlbmpcae
        hp:
          type: string
          x-stoplight:
            id: nftvu6ppd3t9g
        mp:
          type: string
          x-stoplight:
            id: q84kwol6jqfvy
      title: MonsterPart
      type: object
      x-stoplight:
        id: ivlvm5srhnwt7
    MonsterBooty:
      example:
        item: item
        dice: dice
      properties:
        dice:
          type: string
          x-stoplight:
            id: 21m2pyioqz8qv
        item:
          type: string
          x-stoplight:
            id: fpj7q3yf3kcmc
      title: MonsterBooty
      type: object
      x-stoplight:
        id: vzi1iltq23n9j
    MonsterAbility:
      example:
        explain: explain
        kind:
        - kind
        - kind
        name: name
      properties:
        kind:
          items:
            type: string
            x-stoplight:
              id: mm19szy444aak
          type: array
          x-stoplight:
            id: 3a8enq4cie0cp
        name:
          type: string
          x-stoplight:
            id: aure7ngog5rcx
        explain:
          type: string
          x-stoplight:
            id: szq7ryzg6uv23
      title: MonsterAbility
      type: object
      x-stoplight:
        id: lbehakvnwvdvl
    RideStatus:
      properties:
        value:
          type: string
          x-stoplight:
            id: sq517yycwicbe
        int:
          type: string
          x-stoplight:
            id: a2uhwo3ibx1ep
        lang:
          items:
            type: string
            x-stoplight:
              id: dmmjtn2o8ci5o
          type: array
          x-stoplight:
            id: rdrxa64rge1l7
        perc:
          type: string
          x-stoplight:
            id: kxnrp0i3mrjtq
        weak:
          type: string
          x-stoplight:
            id: bwrk8a1dtoqxr
        speed:
          type: string
          x-stoplight:
            id: 42gt4tm1mrjac
      title: MonsterStatus
      type: object
      x-stoplight:
        id: guexz2qy6r0vu
    RideParts:
      properties:
        lv:
          type: string
          x-stoplight:
            id: gvdkk26z4ou5v
        parts:
          items:
            $ref: '#/components/schemas/RidePart'
          type: array
          x-stoplight:
            id: 2kkkuq3peu420
      title: MonsterPart
      type: object
      x-stoplight:
        id: ay803e9oihpu5
    RidePart:
      properties:
        core:
          type: boolean
          x-stoplight:
            id: xq180hdehaem8
        name:
          type: string
          x-stoplight:
            id: wxjavnx8i0r3u
        hit:
          type: string
          x-stoplight:
            id: x2t7ja7eieb38
        damage:
          type: string
          x-stoplight:
            id: vgcf1gk6x3stl
        avoid:
          type: string
          x-stoplight:
            id: 80huks3ma164a
        protect:
          type: string
          x-stoplight:
            id: s5tdobycge8dg
        hp:
          type: string
          x-stoplight:
            id: bvp6jyfjlhswn
        mp:
          type: string
          x-stoplight:
            id: 8muyjm93tsxqu
        lifeRes:
          type: string
          x-stoplight:
            id: tzy51hcu0ax7r
        mindRes:
          type: string
          x-stoplight:
            id: xansx9c32tkta
      title: MonsterPart
      type: object
      x-stoplight:
        id: 798gstelvq035
    GolemAbilitys:
      properties:
        max:
          type: string
          x-stoplight:
            id: 1vslv1kjxzslq
        abilitys:
          items:
            $ref: '#/components/schemas/GolemAbility'
          type: array
          x-stoplight:
            id: chf9633lqm5wb
      type: object
      x-stoplight:
        id: iboycui9ye79u
    GolemAbility:
      properties:
        using:
          type: boolean
          x-stoplight:
            id: l55iewr03e57q
        item:
          type: string
          x-stoplight:
            id: c3ne47jegxtip
        kind:
          items:
            type: string
            x-stoplight:
              id: p0ueut77tik8g
          type: array
          x-stoplight:
            id: 50kiqjvariyeh
        name:
          type: string
          x-stoplight:
            id: mspc0itl0p6ei
        explain:
          type: string
          x-stoplight:
            id: b095iq6ykrs03
      title: MonsterAbility
      type: object
      x-stoplight:
        id: pztp0b98vdra1
    FamiliaStatus:
      properties:
        flv:
          type: string
          x-stoplight:
            id: 09qrvhzl07hcm
        preem:
          type: string
          x-stoplight:
            id: viw42gv1re6vj
        speed:
          type: string
          x-stoplight:
            id: wgel5i3123wm4
      title: MonsterStatus
      type: object
      x-stoplight:
        id: sy462qif0cuk6
    get_monsters_200_response_datas_inner_data:
      anyOf:
      - $ref: '#/components/schemas/CommonMonster'
      - $ref: '#/components/schemas/RideMonster'
      - $ref: '#/components/schemas/GolemMonster'
      - $ref: '#/components/schemas/FamiliaMonster'
      x-stoplight:
        id: h43t4ce402kcs
    get_monsters_200_response_datas_inner:
      example:
        data:
          Status:
            reac: reac
            mind: mind
            imp: imp
            int: int
            speed: speed
            life: life
            weak: weak
            habi:
            - habi
            - habi
            pop: pop
            perc: perc
            preem: preem
            weakValue: weakValue
            lang:
            - lang
            - lang
          Top:
            race: race
            name: name
            lv: lv
          Parts:
          - core: true
            damage: damage
            hit: hit
            mp: mp
            name: name
            hp: hp
            avoid: avoid
            protect: protect
          - core: true
            damage: damage
            hit: hit
            mp: mp
            name: name
            hp: hp
            avoid: avoid
            protect: protect
          Abilitys:
          - explain: explain
            kind:
            - kind
            - kind
            name: name
          - explain: explain
            kind:
            - kind
            - kind
            name: name
          Explanation: Explanation
          Bootys:
          - item: item
            dice: dice
          - item: item
            dice: dice
          Tags:
          - Tags
          - Tags
        id: id
      properties:
        id:
          type: string
          x-stoplight:
            id: zgpqo1gndvfbr
        data:
          $ref: '#/components/schemas/get_monsters_200_response_datas_inner_data'
      type: object
      x-stoplight:
        id: kx9196cfrxmo2
    get_monsters_200_response:
      example:
        datas:
        - data:
            Status:
              reac: reac
              mind: mind
              imp: imp
              int: int
              speed: speed
              life: life
              weak: weak
              habi:
              - habi
              - habi
              pop: pop
              perc: perc
              preem: preem
              weakValue: weakValue
              lang:
              - lang
              - lang
            Top:
              race: race
              name: name
              lv: lv
            Parts:
            - core: true
              damage: damage
              hit: hit
              mp: mp
              name: name
              hp: hp
              avoid: avoid
              protect: protect
            - core: true
              damage: damage
              hit: hit
              mp: mp
              name: name
              hp: hp
              avoid: avoid
              protect: protect
            Abilitys:
            - explain: explain
              kind:
              - kind
              - kind
              name: name
            - explain: explain
              kind:
              - kind
              - kind
              name: name
            Explanation: Explanation
            Bootys:
            - item: item
              dice: dice
            - item: item
              dice: dice
            Tags:
            - Tags
            - Tags
          id: id
        - data:
            Status:
              reac: reac
              mind: mind
              imp: imp
              int: int
              speed: speed
              life: life
              weak: weak
              habi:
              - habi
              - habi
              pop: pop
              perc: perc
              preem: preem
              weakValue: weakValue
              lang:
              - lang
              - lang
            Top:
              race: race
              name: name
              lv: lv
            Parts:
            - core: true
              damage: damage
              hit: hit
              mp: mp
              name: name
              hp: hp
              avoid: avoid
              protect: protect
            - core: true
              damage: damage
              hit: hit
              mp: mp
              name: name
              hp: hp
              avoid: avoid
              protect: protect
            Abilitys:
            - explain: explain
              kind:
              - kind
              - kind
              name: name
            - explain: explain
              kind:
              - kind
              - kind
              name: name
            Explanation: Explanation
            Bootys:
            - item: item
              dice: dice
            - item: item
              dice: dice
            Tags:
            - Tags
            - Tags
          id: id
      properties:
        datas:
          items:
            $ref: '#/components/schemas/get_monsters_200_response_datas_inner'
          type: array
          x-stoplight:
            id: lse5f2m1x65g5
      type: object
    put_monsters_request_data:
      anyOf:
      - $ref: '#/components/schemas/CommonMonster'
      - $ref: '#/components/schemas/RideMonster'
      - $ref: '#/components/schemas/GolemMonster'
      - $ref: '#/components/schemas/FamiliaMonster'
      x-stoplight:
        id: vzm3d33vtero6
    put_monsters_request:
      properties:
        id:
          type: string
          x-stoplight:
            id: ol7t072nuhlkx
        data:
          $ref: '#/components/schemas/put_monsters_request_data'
      type: object
    post_monsters_request_data:
      anyOf:
      - $ref: '#/components/schemas/CommonMonster'
      - $ref: '#/components/schemas/RideMonster'
      - $ref: '#/components/schemas/GolemMonster'
      - $ref: '#/components/schemas/FamiliaMonster'
      x-stoplight:
        id: v7knl941qvvd7
    post_monsters_request:
      properties:
        data:
          $ref: '#/components/schemas/post_monsters_request_data'
      type: object
    delete_monsters_request:
      properties:
        id:
          type: string
          x-stoplight:
            id: 4tv616kf8jfec
      type: object
x-stoplight:
  id: gjim0dod6sd2d
